[package]
name = "contracts"
edition = "2023_11"
version = "0.3.0"

[dependencies]
openzeppelin = "3.0.0"
starknet = "2.13.1"
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v1.0.1" }

[dev-dependencies]
snforge_std = "0.51.2"
assert_macros = "2.13.1"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
casm = true
sierra = true

[[tool.snforge.fork]]
name = "MAINNET_LATEST"
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_10/k6Rkq5Bh1ufyppDuWCK_A"
block_id.tag = "latest"

[tool.fmt]
sort-module-level-items = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[features]
mock_contracts = []
